# Generated by Django 4.1.3 on 2022-12-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=32, null=True, verbose_name='标题')),
                ('abstract', models.CharField(blank=True, max_length=128, null=True, verbose_name='文章简介')),
                ('content', models.TextField(blank=True, null=True, verbose_name='文章内容')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='文章发布日期')),
                ('change_date', models.DateTimeField(auto_now=True, null=True, verbose_name='文章修改日期')),
                ('status', models.IntegerField(choices=[(0, '未发布'), (1, '已发布')], verbose_name='文章保存状态')),
                ('recommend', models.BooleanField(default=True, verbose_name='是否上推荐')),
                ('look_count', models.IntegerField(default=0, verbose_name='文章阅读量')),
                ('comment_count', models.IntegerField(default=0, verbose_name='文章评论量')),
                ('digg_count', models.IntegerField(default=0, verbose_name='文章点赞量')),
                ('collects_count', models.IntegerField(default=0, verbose_name='文章收藏数')),
                ('category', models.IntegerField(blank=True, choices=[(1, '前端'), (2, '后端'), (3, '项目相关')], null=True, verbose_name='文章分类')),
                ('pwd', models.CharField(blank=True, max_length=32, null=True, verbose_name='文章密码')),
                ('author', models.CharField(blank=True, max_length=16, null=True, verbose_name='作者')),
                ('source', models.CharField(blank=True, max_length=32, null=True, verbose_name='来源')),
                ('link', models.URLField(blank=True, null=True, verbose_name='文章链接')),
                ('word', models.IntegerField(default=0, verbose_name='文章字数')),
            ],
            options={
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='Moods',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16, verbose_name='发布人')),
                ('ip', models.GenericIPAddressField(default='120.228.2.238', verbose_name='ip地址')),
                ('addr', models.TextField(null=True, verbose_name='用户地址信息')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='发布时间')),
                ('content', models.TextField(verbose_name='心情内容')),
                ('drawing', models.TextField(blank=True, null=True, verbose_name='配图组，以;隔开')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论数')),
                ('digg_count', models.IntegerField(default=0, verbose_name='点赞数')),
            ],
            options={
                'verbose_name_plural': '心情',
            },
        ),
    ]
