# Generated by Django 4.1.3 on 2022-12-05 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlogV1', '0003_alter_articles_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.FileField(upload_to='article_img/', verbose_name='文章封面地址')),
                ('dominant_hue', models.CharField(blank=True, max_length=16, null=True, verbose_name='封面主色调')),
                ('is_dark', models.BooleanField(blank=True, null=True, verbose_name='是否是深色系')),
            ],
            options={
                'verbose_name_plural': '文章封面',
            },
        ),
        migrations.AddField(
            model_name='articles',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BlogV1.cover', verbose_name='文章封面'),
        ),
    ]
