# Generated by Django 4.1.3 on 2022-12-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogV1', '0004_cover_articles_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, '技术'), (2, '生活'), (3, '西柚宝宝')], null=True, verbose_name='文章分类'),
        ),
    ]
