# Generated by Django 4.1.3 on 2022-12-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogV1', '0006_alter_articles_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, '技术'), (2, '生活')], null=True, verbose_name='文章分类'),
        ),
    ]
