# Generated by Django 4.1.3 on 2022-12-06 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogV1', '0007_alter_articles_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='excellent',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否精选'),
            preserve_default=False,
        ),
    ]
