# Generated by Django 4.1.3 on 2022-12-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogV1', '0009_remove_articles_excellent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Moods',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='cover',
        ),
        migrations.AddField(
            model_name='articles',
            name='cover_id',
            field=models.TextField(default='01', null=True, verbose_name='文章封面ID'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='recommend',
            field=models.BooleanField(default=None, verbose_name='是否上推荐'),
        ),
        migrations.DeleteModel(
            name='Cover',
        ),
    ]
