# Generated by Django 4.1.3 on 2022-12-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogV1', '0010_delete_moods_remove_articles_cover_articles_cover_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='cover_id',
            field=models.TextField(default='01', max_length=16, null=True, verbose_name='文章封面ID'),
        ),
    ]
